### ISSUE TITLE
Reactable on skirolly

### ISSUE THREAD

**Issue by trangdata** [dhimmel/openskistats#17]
Some final reactable things I hope to accomplish for skirolly before submitting to the [Closeread Prize](https://posit.co/blog/closeread-prize-announcement/):

- [x] Show roses properly
- [x] ~Include a toggle to show/hide secondary columns, e.g. cardinal directions ([R example](https://glin.github.io/reactable/articles/examples.html#column-visibility-toggle-button))~ not planned

@dhimmel For the Story, could you make a reactable for just these five mountains:
- Killington Resort
- Pico Mountain Resort
- Whaleback Mountain
- Storrs Hill Ski Area
- Dartmouth Skiway

I'd like (all columns *before* Azimuth) + Rose (so remove all columns under Mean Orientation and Cardinal Directions). And if possible:
- [x] Make background dark or transparent? 🙏🏽

**Comment by joshimmel** [comment]
Looks incredible! So smooth. Some thoughts on text:

Big Sky, Montana, 
- United States (spell it out for foreign readers).

We can do this for other ski areas too! 
- This line item stays around for a little too long (only text / image on page), but maybe intentional.

- Total verts to total vertical

- A bit confused by colored text. I like it, but it has similar colors (like green for distinct ideas). Perhaps green indicates features associated with increased snow retention (north aspect in N hemisphere and vice versa). But green is used for vertical drops at one point, and vertical is in yellow elsewhere. Proposal: Green - good for snow, Yellow - sun exposure / bad for snow, Red/pink: Directional descriptors (compass directions / rose diagrams), then distinct colors for other non-related terms. 

Here are 48 more roses
- From where, random? Or United States? N Hemisphere?


- Could add a transition/motivation for the project earlier on. 
Something like: these data can help us determine the resilience to climate change of different ski areas, in the face of observed and predicted declines in snowfall.

In the table below, you can search for your favorite ski area and explore all of its summary statistics...
- or just take a minute to stop and "smell" the roses. (Finish with something catchy or the meaning of the project - such as “we hope this data will be used to guide winter adventures, assess the climate resilience of distant ski mountains, or to just give you a minute to stop and “smell” the roses.)
